# Generated by Django 3.2.9 on 2021-11-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190518_2346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musicrelease',
            options={},
        ),
        migrations.RemoveField(
            model_name='musicrelease',
            name='release_date',
        ),
        migrations.AlterField(
            model_name='artist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='musicrelease',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
